#
# Automagically generated by Approximatrix Simply Fortran 2.41
#
FC="E:\Simply Fortran 2 full\mingw-w64\bin\gfortran.exe"
CC="E:\Simply Fortran 2 full\mingw-w64\bin\gcc.exe"
AR="E:\Simply Fortran 2 full\mingw-w64\bin\ar.exe"
WRC="E:\Simply Fortran 2 full\mingw-w64\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g -mtune=haswell

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS= -cpp -std=f2008

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\debug.o": ".\debug.f08"
	@echo Compiling .\debug.f08
	@$(FC) -c -o "build\debug.o" $(FFLAGS) ".\debug.f08"
"modules\debug.mod" : "build\debug.o" .EXISTSONLY
	@echo Compiling .\debug.f08
	@$(FC) -c -o "build\debug.o" $(FFLAGS) ".\debug.f08"

"build\main.o": ".\main.f08" "modules\debug.mod"
	@echo Compiling .\main.f08
	@$(FC) -c -o "build\main.o" $(FFLAGS) ".\main.f08"

clean: .SYMBOLIC
	@echo Deleting build\debug.o and related files
	@$(RM) "build\debug.o" "modules\debug.mod" "modules\debug.smod"
	@echo Deleting build\main.o and related files
	@$(RM) "build\main.o"
	@echo Deleting fortiche.exe
	@$(RM) "fortiche.exe"

"fortiche.exe":  "build\debug.o" "build\main.o" "build\fortiche.prj.target"
	@echo Generating fortiche.exe
	@$(FC) -o "fortiche.exe" -static "build\debug.o" "build\main.o" $(LDIR) $(PRJ_LFLAGS)

all: "fortiche.exe" .SYMBOLIC

